appName: gitcall
image:
  repository: hub.corezoid.com/public/gitcall/gitcall
  tag: ""
  pullPolicy: IfNotPresent
  pullSecrets: { }

replicaCount: 1

autoscaling:
  enabled: false
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

config:
  mq:
    vhost: "/gitcall"
    task_vhost: "/dundergitcall"