apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: {{ include "common.Name" . }}-configmap
  labels:
    {{- include "gitcall.labels" . | nindent 4 }}
data:
  gitcall.yaml: |
    {{- tpl (.Files.Get "config.tpl.yaml") . | nindent 4 }}