apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: {{ include "common.Name" . }}-configmap
  labels:
    {{- include "gitcall.labels" . | nindent 4 }}
data:
  gitcall: |
    {{- tpl (.Files.Get "config.json.tpl") . | nindent 4 }}