{{- $tplVals := .Values }}
{{- $_ := set $tplVals "Template" .Template }}

{{- $pgCfg := required "Missing global.postgres value" .Values.global.db.secret.data }}
{{- $mqCfg := required "Missing global.mq value" .Values.global.mq.secret.data }}
{{- $valkeyCfg := required "Missing global.valkey value" .Values.global.valkey.secret.data }}

apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ include "common.Name" . }}-deployment
  labels:
    {{- include "gitcall.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gitcall.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ include "common.spec.strategy.type" . }}
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  {{- if .Values.global.gitcall.autoscaling.enabled }}
  replicas: {{ .Values.global.gitcall.autoscaling.minReplicas }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "gitcall.labels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 40
      serviceAccountName: gitcall-serviceaccount
      initContainers:
        - name: init-wait-postgresql
          image: {{ include "common.initContainers.image" . }}
          command: [ "sh", "-c", "until nc -zvw1 {{ $pgCfg.dbhost }} {{ $pgCfg.dbport }}; do echo waiting for PostgreSQL dependencies; sleep 2; done;" ]
        - name: init-wait-rabbitmq
          image: {{ include "common.initContainers.image" . }}
          command: [ "sh", "-c", "until nc -zvw1 {{ $mqCfg.host }} {{ $mqCfg.port }}; do echo waiting for RabbitMQ dependencies; sleep 2; done;" ]
        - name: init-wait-valkey
          image: {{ include "common.initContainers.image" . }}
          command: [ "sh", "-c", "until nc -zvw1 {{ $valkeyCfg.host }} {{ $valkeyCfg.port }}; do echo waiting for ValKey dependencies; sleep 2; done;" ]
      {{- if not (eq .Values.global.repotype "public") }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecrets.name }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "gitcall.gitcall.imageUrl" . }}
          imagePullPolicy: {{ include "gitcall.gitcall.imagePullPolicy" . }}
          command: [ "/gitcall/gitcall" ]
          args:
            - --config=/gitcall/gitcall.yaml
          ports:
            {{- if .Values.global.serviceMonitor }}
            {{- if .Values.global.serviceMonitor.enabled }}
            - containerPort: {{ .Values.global.gitcall.prometheusPort | default "9100" }}
            {{- end }}
            {{- end }}
          env:
            {{- include "gitcall.container_envs_db" . | indent 12 }}
            {{- include "gitcall.container_envs_mq" . | indent 12 }}
            {{- include "gitcall.container_envs_valkey" . | indent 12 }}
            - name: GOPS_CONFIG_DIR
              value: /tmp
          resources:
            {{- toYaml .Values.global.gitcall.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /gitcall/gitcall.yaml
              subPath: gitcall.yaml
            - name: tmp
              mountPath: /tmp
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop: [ NET_ADMIN, SYS_ADMIN, MAC_ADMIN, SETUID, SETGID, FOWNER, CHOWN, MKNOD ]
      volumes:
        - name: config
          configMap:
            name: {{ include "common.Name" . }}-configmap
        - name: tmp
          emptyDir: { }
      {{- with .Values.global.gitcall.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.gitcall.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
