apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-headless-service
  labels:
    {{- include "gitcall.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "gitcall.selectorLabels" . | nindent 6 }}
  ports:
  - port: {{ .Values.global.gitcall.prometheusPort | default "9100" }}
    targetPort: {{ .Values.global.gitcall.prometheusPort | default "9100" }}
    protocol: TCP
    name: monitoring
