{{- if .Values.global.gitcall.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "common.Name" . }}-hpa
  labels:
    {{- include "gitcall.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "gitcall.fullname" . | quote }}
  minReplicas: {{ .Values.global.gitcall.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.global.gitcall.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.global.gitcall.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
