{{- if .Values.global.gitcall.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "common.Name" . }}-networkpolicy
  labels:
    {{- include "gitcall.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      tier: gitcall-usercode
  policyTypes:
  - Egress
  {{- with .Values.global.gitcall.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
