apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: gitcall-serviceaccount
  labels:
    {{- include "gitcall.labels" . | nindent 4 }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitcall-clusterrole-{{ .Values.global.env | default "prod" }}
  labels:
    {{- include "gitcall.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get", "list", "create", "delete", "update" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "create", "delete", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "pods/log" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "extensions", "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "list", "create", "delete", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "get", "create", "delete", "update", "patch" ]
  - apiGroups: [ "autoscaling" ]
    resources: [ "horizontalpodautoscalers" ]
    verbs: [ "get", "create", "delete", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get", "list", "create", "delete", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get", "list", "create", "delete", "update", "patch" ]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitcall-clusterrole-bind-{{ .Values.global.env | default "prod" }}
  labels:
    {{- include "gitcall.labels" . | nindent 4 }}
subjects:
  - kind: "ServiceAccount"
    name: gitcall-serviceaccount
    namespace: {{ .Release.Namespace }}
    apiGroup: ""
roleRef:
  kind: "ClusterRole"
  name: gitcall-clusterrole-{{ .Values.global.env | default "prod" }}
  apiGroup: ""
