apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gitcall-valkey-policy
  labels:
    {{- include "gitcall.valkey.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "gitcall.valkey.labels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: gitcall
      ports:
        - protocol: TCP
          port: {{ .Values.appPort }}
