apiVersion: v1
kind: ConfigMap
metadata:
  name: pimp-configmap
  labels:
    {{- include "pimp.labels" . | nindent 4 }}
data:
  config: |
    {
      "api": {
        "auth": {
          "gitcall": "{{ required "Missing global.gitcall.secret value" .Values.global.gitcall.secret }}"
        },
        "server": {
          "host": "0.0.0.0",
          "port": 8080
        }
      },
      "k8s": {
        "apply_timeout_ms": 20000,
        "auth": {
          "in_cluster": true
        },
        "image_pull_secrets": [
          {
            "secret_name": "{{ .Release.Name }}-pimp",
            "docker_config": {
              "auths": {
                {{ include "registry.host" . | quote }}: {
                  "username": "{{ .Values.global.gitcall.secret.username }}",
                  "password": "{{ .Values.global.gitcall.secret.password }}"
                }
              }
            }
          }
        ],
        "manage_namespaces": false,
        "manage_networkpolicies": {{ .Values.networkPolicy.enabled }},
        "namespace_cache_ms": 86400,
        "secrets_cache_ms": 86400
      },
      "promserver": {
        "enabled": true,
        "metrics_host": "0.0.0.0",
        "metrics_port": 9100,
        "type": "scrape"
      },
      "sentry": {
        "enabled": false
      }
    }
