apiVersion: "v1"
kind: "Service"
metadata:
  name: pimp-service
  labels:
    {{- include "pimp.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "pimp.selectorLabels" . | nindent 4 }}
    http: "true"
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
