{
 "title": "GitCall Dashboard",
 "tags": [
  "gitcall",
  "simulator"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(gitcall_services,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running GitCall Nodes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gitcall_services{namespace=\"$namespace\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Running GitCall Nodes per lang",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (lang) (gitcall_services_lang{namespace=\"$namespace\"})",
     "legendFormat": "{{lang}}"
    }
   ]
  },
  {
   "title": "Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPM per service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(service) (increase(gitcall_request_duration_seconds_count{namespace=\"$namespace\", service!=\"taskservice\", result=\"done\"}[$__rate_interval])) > 0",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Latency per service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(sum by(service) (increase(gitcall_request_duration_seconds_sum{namespace=\"$namespace\", service!=\"taskservice\", result=\"done\"}[$__rate_interval])) > 0) / (sum by(service) (increase(gitcall_request_duration_seconds_count{namespace=\"$namespace\", service!=\"taskservice\", result=\"done\"}[$__rate_interval])) > 0)",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "RPM Build per lang",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(lang) (increase(gitcall_request_duration_seconds_count{namespace=\"$namespace\", service=\"buildservice\", result=\"done\"}[$__rate_interval])) > 0",
       "legendFormat": "{{lang}}"
      }
     ]
    },
    {
     "title": "Latency Build per lang",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(sum by(lang) (increase(gitcall_request_duration_seconds_sum{namespace=\"$namespace\", service=\"buildservice\", result=\"done\"}[$__rate_interval])) > 0) / (sum by(lang) (increase(gitcall_request_duration_seconds_count{namespace=\"$namespace\", service=\"buildservice\", result=\"done\"}[$__rate_interval])) > 0)",
       "legendFormat": "{{lang}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPM Tasks per lang",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(lang) (increase(gitcall_request_duration_seconds_count{namespace=\"$namespace\", service=\"taskservice\", result=\"done\"}[$__rate_interval])) > 0",
       "legendFormat": "{{lang}}"
      }
     ]
    },
    {
     "title": "Latency Tasks per lang",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(sum by(lang) (increase(gitcall_request_duration_seconds_sum{namespace=\"$namespace\", service=\"taskservice\", result=\"done\"}[$__rate_interval])) > 0) / (sum by(lang) (increase(gitcall_request_duration_seconds_count{namespace=\"$namespace\", service=\"taskservice\", result=\"done\"}[$__rate_interval])) > 0)",
       "legendFormat": "{{lang}}"
      }
     ]
    },
    {
     "title": "RPM Tasks per conv_id",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(group_id, lang) (increase(gitcall_request_duration_seconds_count{namespace=\"$namespace\", service=\"taskservice\", result=\"done\"}[$__rate_interval])) > 0",
       "legendFormat": "{{group_id}} ({{lang}})"
      }
     ]
    },
    {
     "title": "Latency Tasks per conv_id",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(sum by(group_id, lang) (increase(gitcall_request_duration_seconds_sum{namespace=\"$namespace\", service=\"taskservice\", result=\"done\"}[$__rate_interval])) > 0) / (sum by(group_id, lang) (increase(gitcall_request_duration_seconds_count{namespace=\"$namespace\", service=\"taskservice\", result=\"done\"}[$__rate_interval])) > 0)",
       "legendFormat": "{{group_id}} ({{lang}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors per service",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(service, lang) (increase(gitcall_request_duration_seconds_count{namespace=\"$namespace\", service!=\"taskservice\", result=\"error\"}[$__rate_interval])) > 0",
       "legendFormat": "{{service}} ({{lang}})"
      }
     ]
    },
    {
     "title": "Errors Tasks per conv_id",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(group_id, lang) (increase(gitcall_request_duration_seconds_count{namespace=\"$namespace\", service=\"taskservice\", result!=\"done\"}[$__rate_interval])) > 0",
       "legendFormat": "{{group_id}} ({{lang}})"
      }
     ]
    },
    {
     "title": "Errors Tasks per lang",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(lang) (increase(gitcall_request_duration_seconds_count{namespace=\"$namespace\", service=\"taskservice\", result!=\"done\"}[$__rate_interval])) > 0",
       "legendFormat": "{{lang}}"
      }
     ]
    }
   ]
  }
 ]
}