apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.Name" . }}-configmap
  labels:
    {{- include "registry.labels" . | nindent 4 }}
data:
  config.yml: |-
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
    http:
      host: https://{{ .Values.global.gitcall.registry.host }}
      addr: :5000
      headers:
        X-Content-Type-Options: [ nosniff ]
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
