{{- $user := .Values.global.gitcall.secret.username }}
{{- $pass := .Values.global.gitcall.secret.password }}
{{- $haSharedSecret := printf "%s%s" $user $pass }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.Name" . }}-secret
  labels:
    {{- include "registry.labels" . | nindent 4 }}
type: Opaque
data:
  htpasswd: {{ htpasswd $user $pass | b64enc }}
  haSharedSecret: {{ $haSharedSecret | b64enc }}
  {{- if eq .Values.storage.provider "s3" }}
  {{- if and .Values.storage.s3.secretKey .Values.storage.s3.accessKey }}
  s3AccessKey: {{ .Values.storage.s3.accessKey | b64enc }}
  s3SecretKey: {{ .Values.storage.s3.secretKey | b64enc }}
  {{- end }}
  {{- end }}
