apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.Name" . }}-service
  labels:
    {{- include "registry.labels" . | nindent 4 }}
spec:
  ports:
    - port: 5000
      protocol: TCP
      name: registry
      targetPort: 5000
      # nodePort: 32500
  # type: NodePort
  selector:
    {{- include "registry.selectorLabels" . | nindent 4 }}
