apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitcall.postgresSecretName" . | quote }}
  labels:
    tier: "postgres"
    release: {{ .Release.Name | quote }}
  annotations:
    {{- include "gitcall.postgresSecretAnnotations" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.global.db.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  db_name: {{ .Values.global.gitcall.db_name | default "git_call" | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitcall.mqSecretName" . | quote }}
  labels:
    tier: "rabbitmq"
    release: {{ .Release.Name | quote }}
type: Opaque
data:
  {{- range $key, $value := .Values.global.mq.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitcall.valkeySecretName" . | quote }}
  labels:
    tier: "valkey"
    release: {{ .Release.Name | quote }}
type: Opaque
data:
  {{- range $key, $value := .Values.global.valkey.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
