apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.Name" . }}-configmap
  labels:
    {{- include "docker.labels" . | nindent 4 }}
data:
  config: |
    {
      "debug": true,
      "insecure-registries" : [
        "registry-service.{{ .Release.Namespace }}.svc.cluster.local:5000"
      ]
    }
