apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.Name" . }}-configmap
  labels:
    {{- include "docker.labels" . | nindent 4 }}
data:
  config: |
    {
      {{- if eq .Values.global.docker.insecure_registries true }}
      "debug": true,
      "insecure-registries": ["{{.Values.global.gitcall.registry.host}}","{{.Values.global.imageRegistry}}"]
      {{- else }}
      "debug": true
      {{- end }}
    }
