apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.Name" . }}-deployment
  labels:
    {{- include "docker.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "docker.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.global.gitcall.docker.replicaCount | default 2 }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum | quote }}
      labels:
        {{- include "docker.labels" . | nindent 8 }}
        http: "true"
    spec:
      terminationGracePeriodSeconds: 40
      {{- if not (eq .Values.global.repotype "public") }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecrets.name }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ include "gitcall.docker.imagePullPolicy" . }}
          ports:
            - name: docker
              containerPort: 2375
              protocol: TCP
            {{- if .Values.global.serviceMonitor }}
            {{- if .Values.global.serviceMonitor.enabled }}
            - name: monitoring
              containerPort: 9323
              protocol: TCP
            {{- end }}
            {{- end }}
          env:
            - name: DOCKER_TLS_CERTDIR # make daemon use insecure connection
              value: ""
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /etc/docker/daemon.json
              subPath: config
            - name: data
              mountPath: /var/lib/docker/
      volumes:
        - name: config
          configMap:
            name: {{ include "common.Name" . }}-configmap
        - name: data
          emptyDir: { }
      {{- with .Values.global.gitcall.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.gitcall.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
