{{- if .Values.autoscaling.enabled }}
{{- if and (hasKey .Values.global.gitcall "docker") (hasKey .Values.global.gitcall.docker "archs") (.Values.global.gitcall.docker.archs) }}
{{- range $arch, $config := .Values.global.gitcall.docker.archs }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "common.Name" $ }}-hpa-{{ $arch }}
  labels:
    {{- include "docker.labels" $ | nindent 4 }}
    arch: {{ $arch  }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "common.Name" $ }}-deployment-{{ $arch  }}
  minReplicas: {{ $.Values.replicaCount }}
  maxReplicas: {{ $.Values.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ $.Values.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "common.Name" . }}-hpa
  labels:
    {{- include "docker.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "docker.fullname" . | quote }}
  minReplicas: {{ .Values.replicaCount }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
