{{- if and .Values.global.gitcall.docker.archs }}
{{- range $arch, $config := .Values.global.gitcall.docker.archs }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.Name" $ }}-service-{{ $arch }}
  labels:
    {{- include "docker.labels" $ | nindent 4 }}
    arch: {{ $arch }}
spec:
  type: "ClusterIP"
  clusterIP: "None" # headless service
  selector:
    {{- include "docker.selectorLabels" $ | nindent 4 }}
    arch: {{ $arch }}
  ports:
    - port: 2375
      name: docker
      protocol: TCP
      targetPort: docker
{{- end }}
{{- end }}
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "common.Name" . }}-service
  labels:
    {{- include "docker.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  clusterIP: "None" # headless service
  selector:
    {{- include "docker.selectorLabels" . | nindent 4 }}
    default: "true"
  ports:
    - port: 2375
      name: docker
      protocol: TCP
      targetPort: docker
