apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "common.Name" . }}-service
  labels:
    {{- include "docker.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  clusterIP: "None" # headless service
  selector:
    {{- include "docker.selectorLabels" . | nindent 4 }}
  ports:
    - port: 2375
      name: docker
      protocol: TCP
      targetPort: docker
